// <auto-generated />
using System;
using JamyShell.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JamyShell.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200809205946_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6");

            modelBuilder.Entity("JamyShell.Data.Warnings", b =>
                {
                    b.Property<ulong>("WarnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("VictimeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("WarnId");

                    b.ToTable("warnings");
                });
#pragma warning restore 612, 618
        }
    }
}
